### ISSUE TITLE
Flymount bugs [Medium priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#101]
Bug type: Spells

Bug priority: Medium

Bug Description: If you get dced or logout on a flying mount this bugs either the flying or the ground speed of the mount and it becomes 45 % , also riding a flying mount in a zone where u can fly into a zone where u cant fly bugs both the ground and the flying speeds to 45 %. This effect persists untill you switch zones by means of portal entering a dungeon or heartstoning.

How it should work : Flying and ground speeds should be consistent no matter what the situation is.

**Comment by TheGeneral5** [comment]
reported already.
