### ISSUE TITLE
Horde pandaria Riding Trainer Shrine of the two moons [Low priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#102]
Bug type: Open world

Bug priority: Low

Bug Description : There are 2 flying trainers on the Shrine of the Two moons one of them is hostile

How it should work: There should only be a friendly trainer which u can click without having to worry of getting in combat

**Comment by TheGeneral5** [comment]
other trainer doesnt attack unless you attack him, already reported. Please read through the open reports before posting a ton of already reported issues.

**Comment by SeppukuHW** [comment]
Solved.
