### ISSUE TITLE
Horde Transmogrifier npc [medium priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#104]
Bug type : Open world

Bug priority: Medium

Bug Description : Transmogrifier npc in orgrimmar is hostile

How it should work : He should be friendly so you can click him to open the Transmogrify menu

**Comment by TheGeneral5** [comment]
also reported already

**Comment by SeppukuHW** [comment]
Fixed.
