### ISSUE TITLE
Gate of the Setting sun [High priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#105]
Bug Type : dungeons

Bug priority : High

Bug Description: The platforms connecting the several parts of the dungeon are missing

How it should work : There should be this platforms forming a bridge to the next part of the dungeon

**Comment by TheGeneral5** [comment]
already reported.

**Comment by royrosenfeld** [comment]
Fixed

**Comment by TheGeneral5** [comment]
No elevator going up to the third boss, the rest looks good now.
