### ISSUE TITLE
Battle.net Updater [High priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#112]
Bug type : Critical error

Bug priority: High

Bug Description: Everytime u type in your password or login this blizzard updating tool pops up i have uninstalled Battle.net completely but the problem still persists.

How it should work: I should be able to login without this pesky tool bothering me everytime

**Comment by Heartglen** [comment]
I have battlenet install and every game installed from them but I dont get the error, might be something on your part, anyone else?

**Comment by Fonkiemonkie** [comment]
I know from the live realm im not the only one having this problem actualy =)

**Comment by Fonkiemonkie** [comment]
Update : i have deleted all battle.net folders from my pc now i dont get the agent anymore
