### ISSUE TITLE
Lost Of All Professions And major Spells From Talent/ Mounts/ mount Spells ( Critical)

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#117]
Bug name:Lost Of All Professions And Mounts( Critical)
Bug Priority: CRITICAL PRIORITY 
Bug Type: critical error / interface issues
Bug description:When Logon Some Of the Times the entirety of the profession skills an all Mount and mount skill(I.E Spell) is Lost   Also Spells from talents also removed entirely from the spellbook
How is it supposed to work?:Well these are things that can never be undone so this is a Critical bug

**Comment by dutchgringo** [comment]
same for me

**Comment by TheGeneral5** [comment]
Same here, second time its happened.

**Comment by ApexHW** [comment]
That was just some configuration of the PTR that removed some stuff, will be added again if needed.

**Comment by Heartglen** [comment]
imma log in to check it out :p

**Comment by fdh182** [comment]
Same for me
