### ISSUE TITLE
Shrine of Two moons auctioneers

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#119]
Bug: No Auctioneers in shrine of two moons in Pandaria.
Priority: High
Should be 3 auctioneers by the bankers in shrine of two moons

**Comment by Sendoakagii** [comment]
5.4 doesnt have auctioneers :/ there

**Comment by SeppukuHW** [comment]
Creatures spawned.
