### ISSUE TITLE
Inviting to party needs to be done 2 times to work.

### ISSUE THREAD

**Issue by BlokyKappa** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#12]
Bug Priority: Low Prority
Bug Type: interface issues.
Bug description: Bug is annoying, makes you to invite a certain person 2 times in order to get in your party.
How is it supposed to work?: Invite some 1 time instead of 2 times.

**Comment by dobidoberman1** [comment]
Okay you need to elaborate here, I'll explain how:

Does the invitation needs to occur twice otherwise it'll not show up (like the notification)? ////// or perhaps the actual invitiing doesn't kick even though you click accept to the invitiation.

**Comment by blokykappa** [comment]
The message pops up on the target you want to invite, he clicks accept nothing happens. second time he invites it works.
