### ISSUE TITLE
When Die In Pandaria You Have No Ghost Fly Mounts

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#120]
Bug name: When Die In Pandaria You Have No Ghost Fly Mounts(Vale Of Eternal Blossom) 
Bug Priority:HIGH PRIORITY
Bug Type: interface issues
Bug description: When Die In Pandaria You Have No Ghost Fly Mounts(Vale Of Eternal Blossom) so you cant reach your body if you are in a place thats only reachable by flying
How is it supposed to work?: When you die in vale  the ghost has a flyin mount that you can use to reach your body

**Comment by dobidoberman1** [comment]
fixed
