### ISSUE TITLE
Gate Of The Setting Sun No Elevator To reach 3rd boss

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#121]
Bug name: Gate Of The Setting Sun No Elevator To reach 3rd boss
Bug Priority: MEDIUM PRIORITY
Bug Type: PVE dungeon boss 
Bug description: There is no elevator at the 3rd boss so you cant continue 
How is it supposed to work?: Its suppose to have a elevator to reach the boss

**Comment by SeppukuHW** [comment]
Elevator was added.
