### ISSUE TITLE
Warlock Backlash (Normal Priority)

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#13]
Backlash on warlock does not work properly. If incinerate is cast while backlash is active, but was already being cast when backlash activated, then backlash will deactivate and is no longer useable. If target dies before you get a chance to use instant cast incinerate from backlash, you cannot cycle targets and use it on the next, it deactivates.

**Comment by dobidoberman1** [comment]
"Backlash on warlock does not work properly. If incinerate is cast while backlash is active, but was already being cast when backlash activated"

?? Sorry didn't understand that.

**Comment by TheGeneral5** [comment]
OK, so backlash is a buff that activates upon chance if the Warlock has been hit by an enemy. When this is active, it causes the warlocks spell "Incinerate" to become instant cast. If I am already casting incinerate on a target when the backlash buff becomes active and it does the normal 1.5 second cast, the secnd it casts, or the current targeted npc dies, the backlash buff goes away. It should stay active until the buff time runs out, or you cast incinerate as an instant cast.
