### ISSUE TITLE
Bug name: missing npc

### ISSUE THREAD

**Issue by dwingo86** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#133]
Bug name: NPC is missing
Bug Priority:  MEDIUM PRIORITY 
Bug Type: Class monk pand  Quests 
Bug description: jaomin ro is the missing npc to compleet the quest en follow the quest line 
How it should work: npc should be there

**Comment by SeppukuHW** [comment]
If you mean the quest that you duel him @ the pandaren starting area, he is already there. maybe somebody had killed him and he was not re-spawned yet?

It worked fine for me.
