### ISSUE TITLE
Timeless Isle Loot

### ISSUE THREAD

**Issue by Istari369** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#134]
Bug name: Timeless Isle Loot
Bug Priority: MEDIUM PRIORITY
 Bug Type: Class spells / Quests / Item spell / PVE raid boss / PVE dungeon boss / critical error / interface issues 
Bug description:  Any chests, node, reward that you must open (Timeless plate cache) is completely empty.

**Comment by Sendoakagii** [comment]
This was already reported
