### ISSUE TITLE
Item bug

### ISSUE THREAD

**Issue by shmupy** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#137]
[IMG]http://picz.ro/img/af7e71.jpg[/IMG]

As you can see from the picture it does 1 damage and crits for 2 dmg . At it says it procs 2.41 times a minute, but actually prosc every 5 seconds.

**Comment by TheGeneral5** [comment]
1. This is not written in proper format to report a bug.
2. Picture is not viewable, you can drag and drop your screenshot into this comment box, and it will auto upload it to github.

**Comment by shmupy** [comment]
Bug name: Long-lu, Strength of Zuen. Bug Priority: CRITICAL PRIORITY Bug Type:  Item spell  Bug description: He item prosc every 5 seconds and only does 1 damage. 
![wowscrnshot_021315_173358](https://cloud.githubusercontent.com/assets/10995095/6198805/2e0bfd0c-b422-11e4-8ba0-276f1961fea3.jpg)
