### ISSUE TITLE
Warlock Mounts (Low Priority)

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#15]
Bug name: Warlock Mounts
Bug Priority: LOW PRIORITY 
Bug Type: Class spells 
Bug description: Warlock Dreadsteed and Felsteed cannot run on water.
How is it supposed to work?: They should be able to run on water

**Comment by dobidoberman1** [comment]
the effects works with a glyph: 56232, GLYPH OF NIGHTMARES.
