### ISSUE TITLE
Gumi

### ISSUE THREAD

**Issue by fredy432** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#154]
Bug name: Gumi NPC
Bug Priority: HIGH PRIORITY
Bug Type: NPC is friendly when shouldnt be
Bug description: The NPC Gumi is not tameable by horde players. Can you please fix it as its the only Spirit beast wich is not working at all ?

**Comment by Esthellenda** [comment]
Will be fixed on the next bug fix. Thank you for the report.
