### ISSUE TITLE
Foreign language in chat. 

### ISSUE THREAD

**Issue by kleeman7** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#17]
It appears chat has a foreign language in the chat, even tho everything else it english.

**Comment by dobidoberman1** [comment]
Please a screenshot and a reference, i didn't quite understand what you were talking about.

**Comment by kleeman7** [comment]
https://www.dropbox.com/s/8cvfhbzqkqu93o8/WoWScrnShot_012115_113632.jpg?dl=0 
Bug Priority: LOW PRIORITY 
Bug Type: interface issues 
Bug description: Channel names for cities in different language

**Comment by lazerwolf** [comment]
![capture](https://cloud.githubusercontent.com/assets/10629629/5840340/a259c840-a18c-11e4-94bf-8184cae9f4fa.PNG)

and mine. though language set to english

**Comment by dobidoberman1** [comment]
Thanks for bringing that up, will fix it. It's just a dbc issue
