### ISSUE TITLE
Zandalari Warbringer (Townlong Steppes) 

### ISSUE THREAD

**Issue by fredy432** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#181]
Bug name: Zandalari Warbringer (Townlong Steppes) Loot
 Bug Priority: MEDIUM PRIORITY
Bug Type:Loot Table 
Bug description: The NPC Zandalari Warbringer http://www.wowhead.com/npc=69769/zandalari-warbringer , he drops 7Gold 7 Silver and 77 copper only and also is not mounted

**Comment by Esthellenda** [comment]
Fixed. On the next compile will work
