### ISSUE TITLE
VOTE / COINS

### ISSUE THREAD

**Issue by kiresias** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#188]
When I vote I don't get Silver Coins, like 0 Coins...

**Comment by Darkmift** [comment]
+1 on that issue.

Clicking the site...completing captcha...clicking banner...clicking MOP...get wrong vote error 3.

**Comment by SinTakai** [comment]
+ On that, same issue as above. Only first link gives coins.

**Comment by Darkmift** [comment]
Issue is not resolved.
