### ISSUE TITLE
Pandaria Fly Master Trainer A enemy Npc

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#19]
Bug.Pandaria Fly Master Trainer A enemy Npc
Well its Impossible to learn flying atm because the Trainer is A  enemy Npc
Its really annoying to ride a mount on the ground when mobs can basically kill you

**Comment by dobidoberman1** [comment]
Will fix.

**Comment by SeppukuHW** [comment]
Fixed.
