### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by infernalx** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#2]
Bug Priority: HIGH PRIORITY
Bug Type: interface issues
Bug description: After first 3 quests i get in combat bug.
How is it supposed to work?: There should be no combat bug after killed boss

**Comment by dobidoberman1** [comment]
Is it only after completing quests or just that combat stays stuck?

**Comment by anaisa76** [comment]
the combat stays stuck i had it too when i tried as a pandaren. i had to relog for it to go away.

**Comment by dobidoberman1** [comment]
How did it got stuck though? just from fighting mobs? and did it came back again after you entered combat?

**Comment by anaisa76** [comment]
some mobs attacked me i killed then and there was the combat bug after i relogged it didnt appear again.

**Comment by dobidoberman1** [comment]
Alright, then it's just something with the decombat timers. Will fix.

**Comment by anaisa76** [comment]
coolies :) and ty

**Comment by dobidoberman1** [comment]
Made a certain fix, will have to check ingame though. I think the issue was once a player dies and respawns he remains with the aggro, somehow.. so i made it automatically remove combat if he's not in arena or bg.

**Comment by anaisa76** [comment]
it was jsut quest in the starting zone of pandaren

**Comment by kleeman7** [comment]
The combat bug existed on 5.0.5 too, sometimes when running away you get stuck in combat, and also after you kill something it didn't go away.
