### ISSUE TITLE
Timeless Isle Fatigue bug.

### ISSUE THREAD

**Issue by blokykappa** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#20]
Bug Priority: Medium prority.
Bug Type: Critical Error
Bug description: Bug is sorta critical.
How is it supposed to work?: Timeless Isle is not supposed to have a fatigue timer on the island itself.
Screenshots:
http://puu.sh/ePs1f/39f67e40a6.jpg
http://puu.sh/ePrZz/806406c86d.jpg

EDIT: Certain parts dont have the Fatigue bug, but they're small chunks.

**Comment by dobidoberman1** [comment]
I need you to list the parts that has the bug.

**Comment by dobidoberman1** [comment]
Blackguard's Forgotten Cove · The Blazing Way · Cavern of Lost Spirits · Celestial Court · Croaking Hollow · Firewalker's Path · Firewalker Ruins ·  Official horde mini-icon Huojin Landing · Kukuru's Grotto · Misty Strand · Mossgreen Lake · Old Pi'jiu · Ordon Sanctuary · Red Stone Run · Ruby Lake · Shrine of the Black Flame · Three-Breeze Terrace · Timeless Shore ·  Official alliance mini-icon Tushui Landing · Whispershade Hollow

never mind. Got it.

**Comment by dobidoberman1** [comment]
nvm found timeless isle id 6757

**Comment by blokykappa** [comment]
Alrighty no idea what you just wrote to me but ok.

**Comment by dobidoberman1** [comment]
haha, sorry it's just so i can keep up with the research I've just done.

Fixed.
