### ISSUE TITLE
(Interface issues) Raid UI bug [MEDIUM PRIORITY]

### ISSUE THREAD

**Issue by mattdotax** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#201]
When you are in a raid Group after you leave the instance (for example a batteground) it may happen that instead of being removed from the Group you continue to see the Raid UI with the players that were on your Group and you need to relog everytime to fix it.

**Comment by dobidoberman1** [comment]
This is under investigation, thanks for the report.
