### ISSUE TITLE
Priest Talent Void Tendrils

### ISSUE THREAD

**Issue by kleeman7** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#21]
Bug name: Void Tendrils Talent http://www.wowhead.com/spell=108920/void-tendrils
Bug Priority:  MEDIUM PRIORITY
Bug Type: Class spells 
Bug description: Randomly causes you to untarget the mob
How is it supposed to work?: Freeze the target in place for 20 seconds

**Comment by dobidoberman1** [comment]
Ahm.. more details please, I don't quite understand what do you mean by randomly causing you to untarget the mob.

Does the freezing works?
Does the tendrils spawns?
