### ISSUE TITLE
Entering World while Mounted

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#29]
Bug name: Mounted while entering world
Bug Priority: Normal
Bug Type: Mounts
Bug description: When you log off on a flying mount in the air and log back in, the mount only goes normal walking speed (very very slow) until you remount.
How is it supposed to work?: You should be able to go 150-300% speed if mounted upon logging in. Causes issues if you are high in the air when you log off, take 10 minutes to get back down to the ground.

**Comment by dobidoberman1** [comment]
I need someone else to confirm this aswell!

**Comment by TheGeneral5** [comment]
Sendo confirmed it for me, it does the same to him as well.

**Comment by lazerwolf** [comment]
did to me too. logged on mounted on my wyvern. painfully slow.

**Comment by Heartglen** [comment]
yes it happened to me to, my gryphon moves like a turtle upon loggin in ontop of him sso i have to re mount
