### ISSUE TITLE
Isle of Giants Fatigue

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#32]
Bug name: Isle of Giants
Bug Priority: High
Bug Type: Open World
Bug description: Fatigue bug @ Isle of Giants in Pandaria. The second you fly into Bozzles Wreck the fatigue bar comes up.
How is it supposed to work?: Not supposed to be fatigued.

**Comment by dobidoberman1** [comment]
Fixed.
