### ISSUE TITLE
kurenai faction 

### ISSUE THREAD

**Issue by anaisa76** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#38]
bug name: kurenai faction in nagrand
bug priority: high
bug type: Npc
bug description: most all the kurenai npc in nagrand tellar appears as hostile some got quest but isnt giving  them due to being hostile.
how it supposed to work: due to rep  they supposed to be atleast neutral so players can gain rep with them

**Comment by Heartglen** [comment]
Rep is suppose to start at unfriendly. You can attack them if you choose to, but they will not attack without provocation. You start at Unfriendly and then work up to Exalted.

**Comment by anaisa76** [comment]
kk ty
