### ISSUE TITLE
spamin chat

### ISSUE THREAD

**Issue by anaisa76** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#39]
bug name: rested spam in chat
bug priority: high
bug type: chat message
bug description: all the time i am getting the message  you feel rested and you no longer rested. and i got the zzzzz on my char icon thou i am not in any city just questing. the zz i have it since yesterday but no message was appearing and today the message comes with it. spamming my chat in that way.
how it supposed to work: zz appears on the char icon only when you are in a city and the message only appears according to the time you spent resting while in the city

**Comment by dobidoberman1** [comment]
Alright, will fix.

**Comment by anaisa76** [comment]
kk wil lkeep you updated if it goes on.
