### ISSUE TITLE
Rune of Power 90 mage talent

### ISSUE THREAD

**Issue by lazerwolf** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#41]
Bug name: Rune of power
Bug Priority: high
Bug Type: Class spells
Bug description: rune doubles mana regen, no boost to spell power, lasts until logout. and you dont have to stay near rune.
How is it supposed to work?: last 1 minute, be within 5 yards of rune, boost mana regen 75% and spell power 15%

**Comment by dobidoberman1** [comment]
Is the  rune of power's actually visible? I know it's off topic but it relates to a different bug report that we're having.

**Comment by lazerwolf** [comment]
it fades straight away to nothing

**Comment by Heartglen** [comment]
Yea so its like [Healing Spheres] and [Angelic Feather] with the visual bug.

**Comment by dobidoberman1** [comment]
Alright. Gotcha.
