### ISSUE TITLE
The golden lotus

### ISSUE THREAD

**Issue by narmoti45** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#44]
Bug name: The golden lotus
Bug Priority: LOW PRIORITY
Bug Type: Quests
Bug description: you can't speak to the npc Leven Dawnblade

**Comment by dobidoberman1** [comment]
Why? is it hostile?

**Comment by TheGeneral5** [comment]
He is not hostile, he is Neutral. He shows the questgiver exclamation point, but is not clickable. Any time you click him, nothing happens.

![wowscrnshot_012215_124917](https://cloud.githubusercontent.com/assets/10191422/5861206/147ef96a-a235-11e4-89c0-7879546f714b.jpg)

**Comment by SeppukuHW** [comment]
Eh should he actually be there?

He is supposed to be gone after pagoda broke down [ at least that's what wowhead says ], you can now find him only at Siege of Orgrimmar.

**Comment by SeppukuHW** [comment]
He shouldn't even be there. Golden Pagoda was demolished, after 5.4 patch you can find Level in Siege of Orgrimmar, not there.

Probably those NPCs are wrongfully spawned there as of a wrong DB transfer.

Fixed.
