### ISSUE TITLE
Trasnmog Npc Bug

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#45]
Orgrim Npc for transmog is a enemy Npc 
Location : The Drag 
Bug Priority: low

**Comment by dobidoberman1** [comment]
npc id and name please?

**Comment by Sendoakagii** [comment]
ok Name warpweaver dushar

**Comment by TheGeneral5** [comment]
![wowscrnshot_012215_125258](https://cloud.githubusercontent.com/assets/10191422/5861268/9e72d57e-a235-11e4-89e0-66c8a7e27375.jpg)

**Comment by SeppukuHW** [comment]
Fixed.
