### ISSUE TITLE
Upgrade Item

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#46]
Bug name: Upgrade Item
Bug Priority:LOW PRIORITY
Bug Type: interface issues
Bug description: Well when Clicked On noting comes up
How is it supposed to work?:A window suppose to open for you to choose what item/gear that needs to be upgrade

**Comment by Heartglen** [comment]
Gear is upgraded by spending VP [Valor Points], up to 250 valor a upgrade up to a maximun on 4 upgrades, the item should say how many upgrades it should recive
