### ISSUE TITLE
Heroic Dungeons No valor Points

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#47]
Bug name: Heroic Drops No Valor points 
Bug Priority:LOW PRIORITY
Bug Type:PVE dungeon boss
Bug description: Well you suppose to get valor points from heroic dungeons. But none drops
How is it supposed to work?: Well when you kill dungeon boss in heroic mode the bosses usually give Valor points .(provided you don't reach weekly cap)

**Comment by dobidoberman1** [comment]
I think it's only a minor bug in the database, once One0 implement my gm access fix we'll test this.

**Comment by Sendoakagii** [comment]
ok
