### ISSUE TITLE
Gate Of The Setting Sun No Ramp

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#48]
Bug name:Gate Of The Setting Sun No Ramp
Bug Priority:HIGH PRIORITY
Bug Type: / PVE dungeon 
Bug description: Well After the First Boss You cant progress any farther . the script from the ramp seems to be missing  
How is it supposed to work?:
![capture](https://cloud.githubusercontent.com/assets/10622351/5860195/f04e1524-a231-11e4-833c-a43663ff4929.PNG)

**Comment by dobidoberman1** [comment]
Please do not report anything related to either a dungeon, raid or a battleground. These type of stuff are not relevant at this very moment.

Thanks.

**Comment by Sendoakagii** [comment]
kk
