### ISSUE TITLE
Guild Charter

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#49]
Bug Description: When another player has you sign the guild charter, and you hit sign charter, it then tells you that you cant sign your own charter. It still goes through for them, but for the player signing it doesn't show up on the list of signers. 

Priority: Low

**Comment by dobidoberman1** [comment]
Question: will the issue be resolved we lower the quantity of people that are required for the charter sign? like from 10 to 9?

**Comment by TheGeneral5** [comment]
only four people are required to sign to begin with. I've tried signing two different charters for Sendo now, on two separate accounts as well, and each time it said "You cannot sign your own charter"
Also this pop up:
![wowscrnshot_012215_131124](https://cloud.githubusercontent.com/assets/10191422/5862781/8592e212-a242-11e4-9cde-800dbb383d17.jpg)
