### ISSUE TITLE
 selling from inventory to vendor

### ISSUE THREAD

**Issue by anaisa76** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#5]
Bug name: Item selling from inventory to vendor
Bug Priority: High
Bug issue: when selling items to a vendor some does simply grey out and stays inside your inventory.
how it supposed to work: selling item normally without it grey out and stays in the inventory

**Comment by dobidoberman1** [comment]
confirmed, high priorty

**Comment by dobidoberman1** [comment]
Issue has been resolved, will be up within next fixes wave.
