### ISSUE TITLE
Monk Spell: Windwalker's Storm, Earth, and Fire [High Priority][Monk][Windwalker]

### ISSUE THREAD

**Issue by Heartglen** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#50]
The skill itself does not work at all, I target a mob and the spell wont activate

**Comment by dobidoberman1** [comment]
I won't fix it if you won't properly explain the bug and how it should work, closing it for now.

**Comment by Heartglen** [comment]
hope this fixes it, brb more choclate at store :P
