### ISSUE TITLE
blizzard iu message pops up by pressing esc

### ISSUE THREAD

**Issue by anaisa76** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#51]
bug name: by pressing esc blizzard iu  message pops up
bug priority : high
bug type:  pops up message blizzard iu
bug description: when pressing esc  a blizzard iu mesage pops up disabling access to the guild window. i tried relogging and nothing it still there  no access to guild window. some others also seems to have this same bug too.
how it supposed to work.: by pressing esc normally  you get the system window where you can choose options  interface addons and exit game.

**Comment by TheGeneral5** [comment]
Same problem here, now upon logging in I get this and clock no longer shows:

![wowscrnshot_012215_142937](https://cloud.githubusercontent.com/assets/10191422/5862841/216fab16-a243-11e4-9da1-7d56f0ab2b9d.jpg)

**Comment by BlokyKappa** [comment]
I'm having no problems on my hunter nor warrior.
