### ISSUE TITLE
Hunters Trap Spell Dont Work

### ISSUE THREAD

**Issue by Sendoakagii** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#57]
Bug name:Hunters Trap Spell Dont Work
Bug Priority: HIGH PRIORITY
Bug Type: Class spells 
Bug description: When i use Freeze Trap ect It springs the trap but no visual an no spell effects

**Comment by BlokyKappa** [comment]
Wrong, Hunter traps work for me. (survival spec)
http://puu.sh/eU8XF/8e3a753708.jpg

**Comment by Sendoakagii** [comment]
well the 3 other traps works i see now but freeze trap dont work an ofc i dont use dummy to test spells
