### ISSUE TITLE
Arena Timer Crystal

### ISSUE THREAD

**Issue by SeppukuHW** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#60]
Bug name: Arena Timer Crystal

Bug Priority: LOW PRIORITY

Bug Type: Item Spell

Bug description: The crystals are spawning correctly but they don't reduce the timer upon 4/4 clicks etc.

How is it supposed to work?: When you enter an Arena you'll see a crystal, if all 4 players click it the timer goes off so the match can start immediately.

**Comment by Heartglen** [comment]
I was with you on this one, can confirm
