### ISSUE TITLE
Timeless Armor Cache [Gear][Medium Priority]

### ISSUE THREAD

**Issue by Heartglen** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#61]
The timeless cache that Mistweaver Ai sell, Plate, Mail, Leather, and Cloth contain nothing.
Just for info what they contain, here are the wowhead links.

Leather:  http://www.wowhead.com/item=104012/timeless-leather-armor-cache
Plate:  http://www.wowhead.com/item=104009/timeless-plate-armor-cache
Mail:  http://www.wowhead.com/item=104010/timeless-mail-armor-cache
Cloth:  http://www.wowhead.com/item=104013/timeless-cloth-armor-cache

You are suppose to use the case to get a peice of gear specific to your Class Specialization.

So for monks, Mistweavers who use the leather cache, are not suppose to get agility leather, instead they get spirit and intell leather. And windwalkers wont get intell/spirit leather but they will get agility leather.

**Comment by TheGeneral5** [comment]
I can confirm this, but most thing  you can open right now (sack of goods, treasure chests, envelopes) pretty much 90% of things that should contain items when opened, are completely empty.

**Comment by Heartglen** [comment]
Forgot to mention Sepp gave me some timeless coins so i can test out a few caches, and none of em work
