### ISSUE TITLE
Timeless Isle Chests

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#66]
Bug name: Treasure Chest/Items/Loot
Bug Priority:Medium 
Bug Type: Loot
Bug description: When you try to open any chests, lucky red envelopes, or any item caches on timeless isles or other places they contain nothing. 
How is it supposed to work? Supposed to be loot.

**Comment by TheGeneral5** [comment]
![wowscrnshot_012315_001434](https://cloud.githubusercontent.com/assets/10191422/5886067/8f8ccdba-a354-11e4-9d3b-2cf338d2b7b4.jpg)
![wowscrnshot_012315_001621](https://cloud.githubusercontent.com/assets/10191422/5886068/986e52f0-a354-11e4-9de9-41ac9a0881fd.jpg)

**Comment by TheGeneral5** [comment]
Also Burden of Eternity doesnt work.

**Comment by Heartglen** [comment]
Like my prev post on the caches, same that they contain nothing,
