### ISSUE TITLE
Warlock Summon

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#68]
Bug name: Ritual of Summoning
Bug Priority:MEDIUM PRIORITY
Bug Type: Spells
Bug description: While performing the ritual of summoning, it does not open a gate. When the portal is initially clicked on by two party members, nothing happens.
How is it supposed to work? It opens the portal, then two raid/party members have to click on it to open a gate to summon other party.raid members.

**Comment by dobidoberman1** [comment]
Will fix.

**Comment by TheGeneral5** [comment]
rocketh you doith
