### ISSUE TITLE
Alani

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#69]
Bug name: Alani
Bug Priority:LOW PRIORITY
Bug Type: NPC
Bug description: When you try to attack Alani it says invalid target
How is it supposed to work? Should be able to attack.

I'm in a tree here to be high enough to attack it, so its hard to see Alaini
![wowscrnshot_012315_235015](https://cloud.githubusercontent.com/assets/10191422/5886162/95a81dfc-a35a-11e4-9ab2-ceea07965630.jpg)

**Comment by SeppukuHW** [comment]
Have you used the crystal also on him first?

**Comment by TheGeneral5** [comment]
no, no I havent.
