### ISSUE TITLE
quest joining the allaince pandaren

### ISSUE THREAD

**Issue by anaisa76** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#7]
Bug name: join the allaince pandaren
Bug priority: high
bug type: quest
Bug description: when chossing your side as pandaren  i chosen allaince and when i appeared at stormwind  the npc that gives the quest to talk to the king isnt there.
how it supposed to be: when you shoose side and you appear at stormwind as allaince you ind  an npc giving you a quest to talk to king varian so you can join the allaince. followed by another quest to walk with the king getting an explanation to spar with the king and complete the join the allaince quest.

**Comment by lazerwolf** [comment]
same for horde. although my icon says im horde, the dungeon finder,guild finder and pvp button stay grayed out and unavailable until i choose a faction.
