### ISSUE TITLE
Timeless Isles Albatros

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#71]
Bug name: Albatross on Timeless Isle
Bug Priority:LOW PRIORITY
Bug Type: NPC
Bug description: No Albatrosses flying the normal path/none flying at all
How is it supposed to work? Should be Multiple Albatrosses flying around on timeless isle to provide transportation to higher areas. They should circle around the island and swoop in low enough by the Celestial court to hitch a ride.

**Comment by SeppukuHW** [comment]
The albatrosses are spawned, but not properly scripted I suppose.
