### ISSUE TITLE
give mining skill points not working Bug Priority: CRITICAL PRIORITY

### ISSUE THREAD

**Issue by Flamandra** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#73]
mining skill points from rich ghost iron deposit and Kyrapit deposit is not working in Pandaria

Need 600 skill level for Trillium Ore mining and smelt

**Comment by dobidoberman1** [comment]
Only from rich ghost iron and kyrapit deposit?

**Comment by Flamandra** [comment]
Only from ghost and Kyrapit. And my mining skill 570 and my Blacksmith skill 600 was reset. My Character was Selan and i have equip was i made and i have the archiments so pls restore my skills :/ 

     dobidoberman1 <notifications@github.com> schrieb am 0:50 Sonntag, 25.Januar 2015:
   

 Only from rich ghost iron and kyrapit deposit?—
