### ISSUE TITLE
Cradle of Chi-ji

### ISSUE THREAD

**Issue by Esthellenda** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#75]
Bug name: Cradle of Ch-ji named mobs
Bug Priority: MEDIUM PRIORITY
Bug Type: All the named mobs from the island are missing
Bug description: Since the mobs are missing, you cant gain reputation and complete your dailies

**Comment by TheGeneral5** [comment]
Confirmed, Champion of Chi-Ji is the only one that is there.

**Comment by SeppukuHW** [comment]
All of the mobs where added. Chi-ji is fully completable at the moment.
