### ISSUE TITLE
The Eye

### ISSUE THREAD

**Issue by Liirus** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#78]
Bug name: Empty instance . cant change difficulty of insyance .
Bug Priority: SMALL PRIORITY .
Bug Type: everything is gone .
Bug description : cant kill bosses ,and cant get ashes of al'ar

![wowscrnshot_012615_053320](https://cloud.githubusercontent.com/assets/10691388/5890133/bee89a9c-a455-11e4-9065-63a1cb9da1d9.jpg)

**Comment by TheGeneral5** [comment]
Because its on 10man. Set it to 25man and everything will be there. I just did it earlier.
