### ISSUE TITLE
monk lvl 20 Quest practice makes perfect 

### ISSUE THREAD

**Issue by anaisa76** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#8]
Bug name: quest practice makes perfect lvl 20 monk
bug priority: high.
Bug type: quest
bug description:  supposed to talk to master cheng then spar but find a lvl 78 npc in yellow who i wouldnt want to fight to die marking as the quest objective.
how it supposed to be: take the quest talk to master cheng spar with him to complete it and then deliver the quest.

**Comment by SeppukuHW** [comment]
I replaced the npc.

Fixed both quests working.
