### ISSUE TITLE
Profession Rates (Question)

### ISSUE THREAD

**Issue by TheGeneral5** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#82]
Are you planning on upping the rates for Professions as well Dave?
If so, is there any sort of time frame when it will be done?

Just wanted to know before I spend days doing all the profs and having the rates up as soon as I'm done :) Thanks in advance!

**Comment by Heartglen** [comment]
yes, m hesitant in leveling my prof, dont wanna waste lots of time doin nothing with em when they can be leveld 10x later maybe :p

**Comment by Sendoakagii** [comment]
This 1x driving me insane
