### ISSUE TITLE
Transcendence [medium priority][spell][monk]

### ISSUE THREAD

**Issue by kekkultras** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#86]
Transcendence and Transcendence: Transfer don't work

Transcendence don't release a copy of my body for use after Transcendence: Transfer

http://www.wowhead.com/spell=101643/transcendence
http://www.wowhead.com/spell=119996/transcendence-transfer

**Comment by Heartglen** [comment]
umm i cant fonfirm this because t works perfextly fine for me :P

**Comment by kekkultras** [comment]
i have tryied 2 monk but no one work this spell
