### ISSUE TITLE
Succubus Seduction [Medium priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#91]
Bug Type : Spells

Bug priority : Medium

Bug Description: The seduction spell of succubus is not working at all not on autocast neither does it work when trying to cast manualy.

How it should work : If you put this spell on autocast and an player or npc try's to Crowd control you the succubus is supposed to seduce them blowing them a kiss which makes them fall in love with her and unable to do anything.

**Comment by TheGeneral5** [comment]
is the target humanoid? Ive had this work plenty of times.
