### ISSUE TITLE
Soul link [Medium priority]

### ISSUE THREAD

**Issue by Fonkiemonkie** [dobidoberman1/Mystic-5.4.8-Bug-Tracker#96]
Bug type : Talents

Bug priority: Medium

Bug Description: The warlock Talent Soul link is not sharing Damage with your summoned demon and also does not give any heals on spelldamage whatsoever

How it should work: The demon should be taking 20 % of all damage the warlock takes and also should be healed for 3% of all spelldamage the warlock deals to a target.

**Comment by TheGeneral5** [comment]
works for me on destro.
